### ISSUE TITLE
Awaiting approval in review queue for over 5 months

### ISSUE THREAD

**Issue by dhowe** [microsoft/MicrosoftEdge-Extensions#335]
Submitted a minor update to an extension on January 28, and it has yet to be approved. We've since missed two other updates that the other browsers have gotten (I've just updated again in the Edge addons site). 

Are others experiencing these kind of delays for small updates ? Does it have to do with manifest v2 ?

https://partner.microsoft.com/en-us/dashboard/microsoftedge/31156e40-e593-4c71-96fd-c5f4b5cea229/packages/dashboard

**Comment by venkatasai5171** [comment]
_Hello Dhowe,_

Thank you for reaching out. I'm **Venkat** from **Microsoft Edge Extensions Developer Support.**

If you're referring to the extension **AdNauseam** with CRX ID **mlojlfildnehdpnlmpkeiiglhhkofhpb**, I can confirm that your last two submissions were successfully processed:

Submitted: February 21, 2025 at 10:42:10 PM
Completed: February 22, 2025 at 3:19:29 PM

Submitted: January 29, 2025 at 2:40:12 AM
Completed: January 29, 2025 at 12:10:30 PM

Both submissions passed review and were successfully published. 
The latest version is now live on the Add-ons page:
🔗 https://microsoftedge.microsoft.com/addons/detail/adnauseam/mlojlfildnehdpnlmpkeiiglhhkofhpb?form=EDGEAB

If you're referring to a different extension, please share the extension name and CRX ID so we can assist you further.

_Best regards,
Venkat_

**Comment by venkatasai5171** [comment]
Hello Dhowe,

We haven’t received any response from your side, so we’re assuming your query has been resolved. As of now, we are proceeding to close this bug.

If there’s anything further you need, please feel free to reach out to us.

Regards,
Venkat

**Comment by dhowe** [comment]
This is not resolved. Our extension is still stuck in review mode:

<img width="1127" height="503" alt="Image" src="https://github.com/user-attachments/assets/551c1b62-cff9-4e95-bed9-cdb255752bbf" />

and an old version is on theEdge addons page:

<img width="1043" height="633" alt="Image" src="https://github.com/user-attachments/assets/19cc6b9e-ae4c-4e34-a7b7-e42716007624" />

@venkatasai5171 can you re-open ?

**Comment by venkatasai5171** [comment]
Hi Dhowe,

Thank you for reaching out. I understand your query and have forwarded the issue to the engineering team. Once I receive an update, I will promptly convey it to you.

Best regards,
Venkat

**Comment by venkatasai5171** [comment]
Hello Dhowe, 

Our team has reviewed your extension and confirmed that there is no pending submission. It appears your extension is currently in draft state. To proceed with the approval process, please click the Publish button.

For step-by-step guidance on publishing your extension, kindly refer to the official documentation:
https://learn.microsoft.com/en-us/microsoft-edge/extensions/publish/publish-extension

If you have any questions or need further assistance, feel free to reach out.

Best regards,
Venkat
Microsoft Edge Extension Developer Support Team

**Comment by dhowe** [comment]
There is no publish button, apparently bc there is a new requirement that descriptions are greater than 250 words, and, it appears that this needs to be individually changed for EVERY language!? We have over 30 languages - is there no way to batch update this?

**Comment by venkatasai5171** [comment]
Hello Dhowe,

Thank you for reaching out.

As per the official documentation, the minimum requirement for the extension description is 250 words. You can refer to the guidelines here: https://learn.microsoft.com/en-us/microsoft-edge/extensions/publish/publish-extension#step-5-add-store-listing-details-for-your-extension

Additionally, please note that updating the description details and correcting spelling across languages is currently a manual process. This is part of our backlog and will be improved in future updates.

Regards,
Venkat
Microsoft Edge Extension Developer Support

**Comment by venkatasai5171** [comment]
Hello Dhowe,

I hope you're doing well.

We’ve reviewed your feedback and added it to our backlog. As a result, we are proceeding to close this bug.

If you continue to experience any issues, please feel free to raise a new bug and reach out to us.

Regards,
Venkat
Microsoft Edge Developer Support
